### PR TITLE
BES_DrawTrace: Get rid of member variable mCurrentNetSignal

### LINKED ISSUE #762: Board editor: Assert is raised when starting trace at unconnected pad
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.2.0-unstable
Git Revision:     2040eac1afbc0cf1f135884d9c05bf62b156a21c
Build Date:       2020-08-31T20:59:09
Linking type:     static
Unbundled libs:   -
Qt Version:       5.5.1 (built against 5.5.1)
CPU Architecture: x86_64
Operating System: Ubuntu 16.04.7 LTS
Platform Plugin:  xcb
```

##### SUMMARY

When starting to draw a trace at a footprint pad which has no netsignal, an assert is raised (resp. crashes in release mode).

##### STEPS TO REPRODUCE

- Add a device to a board containing pads which are not connected
- Start the "draw trace" tool
- Click on the unconnected pad

##### EXPECTED RESULTS

The trace should start at the pad.

##### ACTUAL RESULTS

The following assert is raised:

https://github.com/LibrePCB/LibrePCB/blob/1f2c0d411a165ae42772b49549dbef78a3c91794/libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp#L566

/cc @5n8ke

### PR DESCRIPTION
**Pull request by 5n8ke**
Fix crash when trying to connect to a pad that is not part of a signal.

Fixes #762

### CODE REVIEW

**Comment by ubruhin** [comment]
Btw, #753 will introduce the same issue again just a few lines below. Maybe better move the exception to outside the if..else if..else if construct to make sure *any* case of a missing netsignal is catched?

**Comment by 5n8ke** [comment]
Actually the assert could be replaced with the exception.

But I want to take a closer look at mCurrentNetSignal, since it's only set when accessing a device pad and not for the other items.

**Comment by 5n8ke** [comment]
mCurrentNetSignal is now removed since the correct netsignal can always be gotten from mCurrentNetSegment.
I introduced the same check in #753 where it definitely caused crashes and would update this PR as soon as the other one is merged.

**Comment by 5n8ke** [comment]
Since #753 is merged, I'll update this PR tonight.

**Comment by ubruhin** [comment]
> Since #753 is merged, I'll update this PR tonight.

Perfect! Afterwards I'll rebase and merge #760 if there are no objections.

**Comment by 5n8ke** [comment]
Not on my side.

**Comment by 5n8ke** [comment]
@ubruhin It's updated to the current master version

File: libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp [hunk 1]
```diff
@@ -918,23 +916,27 @@ void BES_DrawTrace::updateNetpointPositions() noexcept {
     // find anchor under cursor
     GraphicsLayer* layer = mPositioningNetPoint1->getLayerOfLines();
     Q_ASSERT(layer);
-    if (BI_Via* via =
-            findVia(board, mCursorPos, mCurrentNetSignal, {mTempVia})) {
+    NetSignal* netsignal = &mCurrentNetSegment->getNetSignal();
+    // NOTE(5n8ke): netsignal must not be nullptr, since a connection should
+    // only be made to the current NetSignal
+    Q_ASSERT(netsignal);
```
Comment (ubruhin) [inline libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp:922]: `netsignal` can't be `nullptr` since it was constructed by taking the address of an object, so no check is needed:

```suggestion
    NetSignal* netsignal = &mCurrentNetSegment->getNetSignal();
```

But actually, one more time, simply don't convert the reference to a pointer here, then it's obvious that it can't be `nullptr` :smiley: :

```suggestion
    NetSignal& netsignal = mCurrentNetSegment->getNetSignal();
```

Then use `&netsignal` where you really need a pointer.

File: libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp [hunk 2]
```diff
@@ -976,11 +978,14 @@ void BES_DrawTrace::layerComboBoxIndexChanged(int index) noexcept {
...
-    Point            startPos = mFixedStartAnchor->getPosition();
-    BI_FootprintPad* padAtStart =
-        findPad(board, startPos, nullptr, mCurrentNetSignal);
-    if (findVia(board, startPos, mCurrentNetSignal) ||
+    Board&     board     = mPositioningNetPoint1->getBoard();
+    Point      startPos  = mFixedStartAnchor->getPosition();
+    NetSignal* netsignal = &mCurrentNetSegment->getNetSignal();
+    // NOTE(5n8ke): netsignal must not be nullptr, since a connection should
+    // only be made to the current NetSignal
+    Q_ASSERT(netsignal);
```
Comment (ubruhin) [inline libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp:986]: Same here:

```suggestion
    NetSignal& netsignal = mCurrentNetSegment->getNetSignal();
```

**Review by ubruhin — COMMENTED** [review]
Although it turned out that the "fix" is actually not needed (sorry...), I always like removing members since usually it reduces complexity and error-proneness :smiley:

File: libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp (hunk 1 above)
Comment (5n8ke) [reply libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp:922]: I chose to use a pointer here since all the following find* take a pointer as the netsignal parameter.
The check is not needed, but I added the asserts as a sanity check to make it explicit, since a null pointer was previously possible with mCurrentNetSignal.

Comment (ubruhin) [reply libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp:922]: Hmm okay - to be honest, I don't like it (IMO a reference would be much cleaner) but this time I'll turn a blind eye :wink:
